version: "3.4"

services:
  frontend:
    restart: always
    image: "ghcr.io/dedogmadao/dt-frontend/dt-frontend:gitcoin-latest"
    environment:
      - BACKEND_URL
      - ROBOTS_TXT
    command: sh /app/frontend/src/run.sh
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: ddd_network