version: "3.4"

services:
  frontend:
    restart: always
    image: "ghcr.io/dedogmadao/${REPOSITORY_NAME}/${REPOSITORY_NAME}:${BRANCH}-latest"
    environment:
      - BACKEND_URL
      - ROBOTS_TXT
    command: echo $ROBOTS_TXT > /app/frontend/src/public/robots.txt && npm run up

networks:
  default:
    external:
      name: ddd_network