name: Deploy manualy 

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: pull latest code
        uses: actions/checkout@v3

      - name: build step
        run: docker build -t ghcr.io/dedogmadao/dt-frontend/dt-frontend:${{ github.ref_name }}-latest .

      - name: login to docker registry
        run: echo ${{ secrets.PERSONAL_GITHUB_TOKEN }} | docker login ghcr.io -u flokibb --password-stdin

      - name: push docker image to package registry
        run: docker push ghcr.io/dedogmadao/dt-frontend/dt-frontend:${{ github.ref_name }}-latest
 
  update_services:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: run command on remote
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SSH_ACTION_HOST }}
        username: ${{ secrets.PROD_SSH_ACTION_USER }}
        key: ${{ secrets.PROD_SSH_ACTION_KEY }}
        port: ${{ secrets.PROD_SSH_ACTION_PROT }}
        script: |
          export DOMAIN=${{ secrets.PROD_DOMAIN }}
          export BACKEND_URL=${{ secrets.PROD_BACKEND_URL }}
          export ROBOTS_TXT=${{ secrets.PROD_ROBOTS_TXT_FILE }}
          curl -H "Authorization: token ${{ secrets.PERSONAL_GITHUB_TOKEN }}" https://raw.githubusercontent.com/DeDogmaDao/dt-frontend/master/docker-compose.deploy.yml > docker-compose.deploy.yml
          echo ${{ secrets.PERSONAL_GITHUB_TOKEN }} | docker login ghcr.io -u flokibb --password-stdin
          docker network create ddd_network || true
          docker volume create --name=mediafiles || true
          docker volume create --name=staticfiles || true
          docker volume create --name=database || true
          docker rmi -f ghcr.io/dedogmadao/dt-frontend/dt-frontend:master-latest || echo "Ok"
          docker pull ghcr.io/dedogmadao/dt-frontend/dt-frontend:master-latest
          docker-compose -f docker-compose.deploy.yml down
          docker-compose -f docker-compose.deploy.yml up -d
          rm -rf docker-compose.deploy.yml
          
